### ISSUE TITLE
CustomUsers's user_type field is using UserType enum's names instead of values

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#100]
User backend accepts enum's names instead of values for user_type field.

So with enum like:
EMPLOYE = 'Employee'
MANAGER = 'Manager'
the user_type is stored in model as "EMPLOYEE" and "MANAGER", because it's using the wrong attribute from enum.

This is problematic, because if we change the string value (e.g. translation) nothing will be affected.

**Comment by dybi** [comment]
The solution could be to override `UserType`'s `__str__` to return `value` instead of `name`. Thanks to that, what is stored in the DB will not depend on any translations, but the display values will.

**Comment by rwrzesien** [comment]
Wait, whooaaat? That is correct that the value stored is "EMPLOYEE" and "MANAGER" because this is the key, and what should be displayed is value like 'Employee' or 'Manager' which can change or be translated.  The point is that keys should not change.
Or am I missing something here?
