### ISSUE TITLE
As a manager, when I create a project and don't assign myself to it, I can't edit it.

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#118]
As a manager, when I create a project and don't assign myself to it, I can't edit it. Is this how it should work?

**Comment by rwrzesien** [comment]
@Karrp Any updates on that ^ ?

**Comment by Karrp** [comment]
Maybe automatically add this user as a manager to this project then if user will not make any changes in managers list then he will be still in this project.

Additionally we should change way of editing the list of managers to be more intuitive 
maybe something like:

**Managers**
 - [ ] user
 - [x] manager
 - [ ] user
 - [ ] user
 - [x] manager
