### ISSUE TITLE
Superuser is not made Admin by default

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#125]
After creating superuser with manage.py he is not an Admin but a Manager instead.

**Comment by rwrzesien** [comment]
I think those two shouldn't be mixed. Django admin is a specific user that has access to admin panel and it should not access front page. However front page user type admin is a different concept and should not have access to admin panel.

**Comment by maciejSamerdak** [comment]
Sure, a Sheetstorm admin doesn't have to be an actual Django admin.
However, I think Django admin should be a Sheetstorm admin by default. It makes sense to me, that superuser is automatically granted the most privileged user status in the app, without necessity of doing that himself in Django's admin panel.

At least I believe that was the initial idea - that Sheetstorm's admin type is primarly used with superusers.

> Calling @MartynaAnnaGottschling and @Karrp for confirmation! Repeat: calling @MartynaAnnaGottschling and @Karrp for confirmation!

**Comment by rwrzesien** [comment]
Well if you want to try this go ahead :) Please remember that there can be several ways of creating Django admin user so I think best way would be either overriding `save()` method or do this in `post_save` signal attached to `User`.

**Comment by maciejSamerdak** [comment]
This was an inaccurately identified issue, which was expanded in #159
