### ISSUE TITLE
In creating new project site its impossible to enter correct date if you don't know date format

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#155]
There should be tool tip or something like datepicker.

![image](https://user-images.githubusercontent.com/37847362/56802609-c8494d00-6820-11e9-9d88-b09a708cc33e.png)

**Comment by rwrzesien** [comment]
@Karrp For some reason datepickers are not working at the moment, it is related also to the bug with delete button not working, I have described how to fix it here https://github.com/Code-Poets/sheetstorm/pull/160#discussion_r279171513. After applying those changes they should work again and if you use them they will put date into fields in correct format.

Also, it would be good to add date format as a hint in `help_text`, this is a good task for @Szymiks . If possible please make it dynamic, so the same value is used in `ProjectForm.Meta.widgets` and in `help_text` (it might be defined in constants for example).

**Comment by Karrp** [comment]
Ok I created new issue for hint in `help_text` #163 as fast workaround.
