### ISSUE TITLE
We can create project that shares name and start date with existing one, but we cannot see it on project list.

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#170]
This also seems to generate an issue in report list. If we create multiple project with same name, POST causes a crash in report list due to `MultipleObjectsReturned`.

Before fixing this issue we must consider whether project name should be unique or not.

**Comment by rwrzesien** [comment]
@Karrp @maciejSamerdak 
> Before fixing this issue we must consider whether project name should be unique or not.

Do you guys have a decision? Looks like an issue easy to fix but decision is needed.

**Comment by Karrp** [comment]
Two (or more) projects can have same name.

**Comment by rwrzesien** [comment]
This will be resolved in https://github.com/Code-Poets/sheetstorm/pull/274.

@Szymiks Please add info to your pull request that it also resolved this issue. I have added a test to your branch to prove that. Commit id is 98eb8e452b0b9930c3cf235c4091b6eb0501e20b.

@Karrp @maciejSamerdak The only problem now is that it looks simply not clear when there are two identical names in the form select projects list. I have no idea for now how to avoid this, as we don't want to expose ID for sure, and other project info (like start/stop date) can also be the identical for two projects.

**Comment by Karrp** [comment]
But one project can be closed, another active.
Maybe we should add additional info field or something to every project in the future.

**Comment by maciejSamerdak** [comment]
Closing, because the issue is already resolved.
