### ISSUE TITLE
[UX] make calendar always visible instead of popup

### ISSUE THREAD

**Issue by michalpiasecki1** [Code-Poets/sheetstorm#184]
Right now, calendar on /reports/ page is a popup, when users clicks on date input field. It can be visible all the time, for example on the left, as on attached picture. It would save time when adding entries for past days.

![image](https://user-images.githubusercontent.com/41307518/57455247-04da6700-726b-11e9-85e9-b0acb3b4e03d.png)

**Comment by kbeker** [comment]
This view will be completely different, so for this moment I'm closing this.
