### ISSUE TITLE
Wrong hour formatting in admin's report editing view

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#187]
The minutes and hours are separated by comma instead of a colon.

If we are to keep the Decimal type for work hours, there was a special field defined for this purpose for report serializer. Perhaps it would be possible to connect it to basic form?

**Comment by dybi** [comment]
@maciejSamerdak @kbeker @Karrp is this issue still valid? If not, we should close it.

**Comment by kbeker** [comment]
This is definitely no longer valid. Thank @dybi. Closing :lock:
