### ISSUE TITLE
[UX] date field top/bottom margin

### ISSUE THREAD

**Issue by michalpiasecki1** [Code-Poets/sheetstorm#188]
date input is not on the center of the field

![image](https://user-images.githubusercontent.com/41307518/57461517-75878080-7277-11e9-80e3-d58bbbdc09c5.png)
![image](https://user-images.githubusercontent.com/41307518/57461606-9d76e400-7277-11e9-985c-12df1a98749c.png)

**Comment by kbeker** [comment]
Already done.
