### ISSUE TITLE
Admin can change report's author

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#192]
Despite admin being an admin, I believe author field is the one field he shouldn't be able to change in report. I cannot think of a good reason why this would be necessary, how can a user upload a report that's not his? Why would admin apply someone's report to someone else? If such situation would ever occur, he can always use Django's admin site.

**Comment by rwrzesien** [comment]
@maciejSamerdak 
> Why would admin apply someone's report to someone else?

Reports send to clients :)
