### ISSUE TITLE
Deceptive sidebar collapse icon

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#198]
Related #301 

This icon can looks like previous page button.
![image](https://user-images.githubusercontent.com/37847362/57610850-dbbf1c80-7571-11e9-8914-575ad9a509c4.png)

Maybe icon like that would be better?
![image](https://user-images.githubusercontent.com/37847362/57611108-6869da80-7572-11e9-8d8a-18aa3acda907.png)

Or ask @wyspiansky87 

Should be done:
 ------------
 - change icon to more intuitive
 - change button location

**Comment by kbeker** [comment]
Button already deleted. Closing
