### ISSUE TITLE
Project should have customisable task activity list

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#204]
Should be done:
 ------------
 - Project should have it's own, customisable list of task activities
 - When creating or editing a report, the employee cannot select a task activity, that's outside of project's list
 - Project can have special task activities

**Comment by rwrzesien** [comment]
My idea for that was:
1. Add nullable field `project` to `TaskActivityType` which will be FK to `Project`.
2. There should be a list of default `TaskActivityTypes` which `project` set to `null`.
3. When Manager/Admin creates a project, a copy of those defaults is created for project.
4. Then Manager/Admin can modify the `TaskActivityTypes` within related to project, without modifying defaults. He can CRUD them in any way without making changes to other projects too.

@maciejSamerdak @dybi What do you guys think?

**Comment by Karrp** [comment]
It seems to me that it can cause more problems than benefits.

**Comment by dybi** [comment]
@rwrzesien I would need to research a bit on that
@Karrp - like all new features, right? ;)

**Comment by rwrzesien** [comment]
@dybi Sure, I would be happy to discuss the idea or its improvements, but this is just an idea, which still requires decision ;)
@Karrp Could you please be more precise - what problems exactly do you mean?

**Comment by Karrp** [comment]
If the employee does some work which type of activity does not appear in the default list, the problem will appear.
I understand that then he must set `TaskActivityType` as `other` and contact the manager?
Maybe you have better solution.

I do not remember any more problems so I think we can implement this idea.

 ----
By the way, you will need to give the manager opportunity to add new activities in such a way that two managers do not add two activities with different names but significant ones.

**Comment by kbeker** [comment]
@Karrp is this issue still valid? @maciejSamerdak is this a request from client?

**Comment by Karrp** [comment]
Issue is valid.
It's nice to have this feature.
