### ISSUE TITLE
Change the field type of `work_hours` to `DurationField` 

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#213]
Original cause explained in https://github.com/Code-Poets/sheetstorm/pull/137/files#r285399800

Change the field type of `work_hours` to `DurationField` https://docs.djangoproject.com/en/2.2/ref/models/fields/#durationfield:
1. Create new field of type `DurationField` with different name.
2. Prepare data migration to migrate from `work_hours` to the new field.
3. Remove `work_hours` field.
4. Rename new field to `work_hours`.
5. Make sure all tests passed.
6. It would be great to make some manual testings before merging.

Yes, it would require 4 migrations to do this correctly. It would be also great to review current data and make sure that everyone using the system meant the same when adding hours, so we know how to migrate data correctly.

**Comment by rwrzesien** [comment]
I have found the similar issue already being created https://github.com/Code-Poets/sheetstorm/issues/72. It says that we should keep work hours in `TimeField` (https://docs.djangoproject.com/en/2.2/ref/models/fields/#timefield) and is kept as `datetime.time` in Python. But it disallows us some basic calculations, which is allowed in `datetime.timedelta` type user by `DurationField`. So I suggest keeping this one and closing https://github.com/Code-Poets/sheetstorm/issues/72.

**Comment by maciejSamerdak** [comment]
Would there be issues with migrating existing data in production?

**Comment by kbeker** [comment]
@maciejSamerdak It should not be, but we have to do data migration with steps which @rwrzesien mentioned above. If you have free time you can do it @maciejSamerdak. But if you don't I will do it in free time today, or tomorrow.
