### ISSUE TITLE
Validation for sum of hours per day being less than 24 does not work on report creation.

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#221]
This is most likely caused because this validation wasn't implemented for REST-based serializer, which is currently in use in `CustomReportList` and `CustomReportDetail`

Should be done:
 ------------
 - serializer should include the 24 hours validation

**Comment by maciejSamerdak** [comment]
I've ran into an issue: I tried to override `validate` in serializer to check for the 24 hour constraint. However, the way it's handled right now, the *author* is passed in view on post, when `save` is called from serializer. So there is no *author* in data when `validate` is called and because of that, I cannot check for author's other reports.

I'm trying to figure it out right now, it's a serious complication in how serializer should be validated and saved.

**Comment by rwrzesien** [comment]
@maciejSamerdak Maybe it would be simpler to refactor this view to Django views and get rid of serializer there? :)
