### ISSUE TITLE
User's birth date has no limits

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#225]
We can currently employ children, embryos and time travelers. It's nice that we don't discriminate, but this might be a little overboard and illegal.

Should be done:
 ------------
 - Birth date should be earlier than 18 years ago
 - Birth date shouldn't be earlier than at least the beginning of 20th century
 - 
 -

**Comment by dybi** [comment]
closing, as merge failed to close automatically
