### ISSUE TITLE
Change employees.views.ReportDetail to django view (UpdateView)

### ISSUE THREAD

**Issue by dybi** [Code-Poets/sheetstorm#245]
Should be done:
 ------------
 - change views
 - adapt tests
 - 
 -

**Comment by dybi** [comment]
@Szymiks - yellow card for not creating and self-assigning the issue ]:->

**Comment by Szymiks** [comment]
> @Szymiks - yellow card for not creating and self-assigning the issue smiling_imp

Sorry ref:)
