### ISSUE TITLE
Unify validator usage in models

### ISSUE THREAD

**Issue by dybi** [Code-Poets/sheetstorm#250]
Right now there is no structured way of validators' usage. Part of the validation is done by passing `validator`s to models' fields arguments, part of validation is done in `clean` method.

Should be done:
 ------------
 - Single field related validation should be done via `validator` passed as argument. ie.
```python
email = models.EmailField(
    CustomUserModelText.EMAIL_ADDRESS, 
    max_length=constants.EMAIL_MAX_LENGTH, 
    unique=True,
    validators=[custom_validate_email_function]
)
```
 - Validation related to more fields (or related to inter-dependency between fields) should be done in `clean()` method, ie.
```python
    def clean(self) -> None:
        super().clean()

        if (
            hasattr(self, "author")
            and isinstance(self.work_hours, Decimal)
            and self.author.report_set.get_report_work_hours_sum_for_date(self.date, self.pk) + self.work_hours > 24
        ):
            raise ValidationError(
                message=ReportValidationStrings.WORK_HOURS_SUM_FOR_GIVEN_DATE_FOR_SINGLE_AUTHOR_EXCEEDED.value
            )
```

**Comment by kbeker** [comment]
@dybi @rwrzesien I think, that only validatores provided by django should be passed as a parameter `validators` in field description. When we will add there custom validatores it might cause problems in future if we want to modify this validator or even delete it. All custom validation should be done in `clean` method because it won't be visible in any migration and this is simply in modification.

**Comment by rwrzesien** [comment]
> When we will add there custom validatores it might cause problems in future if we want to modify this validator or even delete it. 

Yes, that's the "feature" I forgot about, and its really annoying. After thinking it through I think it can be resolved by modifying migration which uses it, but not everyone would like this approach. How about discussing this on live?

There is also a case - sometimes validation is needed for model, which means it will be always triggered, and sometimes it is specific for current view, so it can be implemented in form only. We should remember about this possibility too.

**Comment by kbeker** [comment]
After discuss we decided to keep validators in model fields. We proved, that deleting validators from old migrations will not affect on database. If any of custom validations will go beyond normal field validations then should be placed in `clean` method inside model class.
