### ISSUE TITLE
Update postgres installation for Mac in README

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#259]
I've encountered few issues while trying to update my postgres to 11.3. In order to recreate the flow from README, `-U` flag with `postgres` value had to be added at `initdb` call. I also had to remove the directory beforehand, since it wasn't empty? Can't tell if that happens on clean install though. Perhaps installation runs differently due to newer version?

Perhaps it needs to be further researched, but at the moment it's of lower priority. Right now I'm dropping this as a memo.

Should be done:
 ------------
 - Add information about removing `/usr/local/var/postgres` prior to 'initdb' call
 - Add `-U postgres` to `initdb` call
 - Well, obviously, version information needs to be changed to 11.3 as well
 -

**Comment by kbeker** [comment]
@maciejSamerdak if you are not doing now this task please unsigned yourself.
