### ISSUE TITLE
Group days and add daily hours to exported xlsx file.

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#268]
Alicja reported a need for an additional column with the sum of hours of the day. In addition, she asked to mention single day only once.

before:
<img width="365" alt="Zrzut ekranu 2019-06-3 o 12 00 08 PM" src="https://user-images.githubusercontent.com/37847362/58817984-5b01b680-862d-11e9-9a35-37a79404ee16.png">

Should be done:
 ------------
 - 
 - 
 - 
 -

**Comment by Szymiks** [comment]
I was working with `openpyxl` documentation -> https://openpyxl.readthedocs.io/en/stable/
