### ISSUE TITLE
Create release notes for tag 0.1

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#27]
What's included in this tag
something like here:
https://github.com/golemfactory/concent/blob/master/RELEASE-NOTES.md

**Comment by MartynaAnnaGottschling** [comment]
@Karrp that link is not working. Only for me?

**Comment by Karrp** [comment]
This link should work:
https://github.com/golemfactory/concent/blob/master/RELEASE-NOTES.md

**Comment by Karrp** [comment]
Should work now
