### ISSUE TITLE
Missing Code Poets logo

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#285]
Should be done:
 ------------
 - add Code Poets logo in every view (in base i think)

**Comment by kbeker** [comment]
@Karrp 

> ## Should be done:
> * add Code Poets logo in every view (in base i think)

Which means where exactly we should add it? Please provide screenshot with a place where it should be added.

**Comment by wyspiansky87** [comment]
comment

**Comment by Karrp** [comment]
> @Karrp
> 
> > ## Should be done:
> > 
> > * add Code Poets logo in every view (in base i think)
> 
> Which means where exactly we should add it? Please provide screenshot with a place where it should be added.

I asked @wyspiansky87 for help

**Comment by kbeker** [comment]
I asked Michał and he told that logo might be in the left top corner instead of person icon.
