### ISSUE TITLE
Protection area of ​​Sheet Storm logotype

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#287]
Related #289 

![image](https://user-images.githubusercontent.com/37847362/59025287-21f75b00-8854-11e9-8493-2819972a1782.png)

Should be done:
 ------------
 -  increase margins (especially on the right side)

**Comment by kbeker** [comment]
@Karrp 

> ## Should be done:
> * increase margins (especially on the right side)

How big margins should be? Please provide screenshot as a example.

**Comment by Karrp** [comment]
@wyspiansky87 can you help?

**Comment by kbeker** [comment]
@Karrp please ask him and add here more details
