### ISSUE TITLE
Application responsiveness

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#288]
App should fit to every size and orientation of screen or window

Should be done:
 ------------
 - check  with small window, big screen, phone screen
 - 
 - 
 -

**Comment by kbeker** [comment]
@Karrp 

> App should fit to every size and orientation of screen or window
> 
> ## Should be done:
> * check  with small window, big screen, phone screen

Do we really want to support phone screens also? I think, that it might be big thing to adapt application also to be shown in phone screens. @rwrzesien what do you think?

**Comment by Karrp** [comment]
Yes, I think so.
People use phones to make reports after work in public transport.
