### ISSUE TITLE
Members field in project editing form should be larger

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#290]
The field which allows you to choose project members should be larger and/or manually expandable.

Should be done:
 ------------
 - Widget used for members picking should be larger
 - Widget used for members picking should be expandable
 - 
 -

**Comment by Karrp** [comment]
Or maybe change method of choosing project members and managers.
For something similar to this:
![image](https://user-images.githubusercontent.com/37847362/59606684-0d4b7a80-9112-11e9-8868-3f90987547d2.png)

**Comment by Karrp** [comment]
Method was changed but the rest is stil valid.

**Comment by Merrique** [comment]
Included in https://github.com/Code-Poets/sheetstorm/issues/492
