### ISSUE TITLE
Add some information about Code Poets to the home page.

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#291]
Should be done:
 ------------
 - add links to Code poets pages like jira, rocket etc.
 - add some information about our company

**Comment by kbeker** [comment]
@Karrp 



> ## Should be done:
> * add links to Code poets pages like jira, rocket etc.
> * add some information about our company

What information? Please give text which should by in this page. Should it be editable?

**Comment by Karrp** [comment]
for example:
https://j.codepoets.it
https://s.codepoets.it
https://codepoets.rocket.chat

**Comment by kbeker** [comment]
@Karrp And thats all what we should add at home page? Is this a request from client?
