### ISSUE TITLE
Change `extract_year_and_month_from_url` template filter to use regexp

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#295]
Original comment:
https://github.com/Code-Poets/sheetstorm/pull/292#discussion_r291612121

Current implementation of `extract_year_and_month_from_url` is a little bit fragile. If url change, it might not work. We could change it to use url definition (please verify if this is possible) and regex for matching needed values.

This is low priority.

**Comment by Szymiks** [comment]
I will try to do this
