### ISSUE TITLE
Tests for report list's get methods get a Queryset as instance in serializer.

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#30]

**Comment by rwrzesien** [comment]
@maciejSamerdak Could you please provide more info? Which branch is it and which test exactly? Also if you mention HTTP method GET please capitalize it so it can differ from "get" word.

**Comment by rwrzesien** [comment]
@maciejSamerdak Please update ^^.

**Comment by maciejSamerdak** [comment]
This issue is outdated. It didn't resurface until now and it definitely won't resurface after switching to Django generic view.
