### ISSUE TITLE
Hyperlinks from report description could be carried over to .xlsx export

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#307]
Excel supports hyperlinks. Perhaps we could take an advantage out of this and carry over hyperlinks from markdown formatting?

Should be done:
 ------------
 - Exported .xlsx report list should contain hyperlinks in description

**Comment by dybi** [comment]
@Code-Poets/sheetstorm,  it seems that in `Excel`, we cannot have a part of the description an URL, at least in "hand-made" spreadsheet[click](https://superuser.com/questions/428299/hyperlinking-a-piece-of-text-in-excel). I seriously doubt it is possible at al with python libraries... The question is: do we accept having a whole cell a hyperlink (but then - what if `description` contains more of them) or do we drop this issue?

**Comment by Karrp** [comment]
We are using .xlsx not .xls

**Comment by Karrp** [comment]
It is not necessary.
The customer did not ask for it.

**Comment by Karrp** [comment]
It is not necessary.
The customer did not ask for it.

![image](https://user-images.githubusercontent.com/37847362/59606377-41726b80-9111-11e9-862e-4fcf4ad4e6b6.png)
