### ISSUE TITLE
Better export of reports to XLSX

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#310]
Suggestions arising during the interview with Adrian.

Should be done:
 ------------
 - [x] employees mentioned only by name and first letter of the surname
 - [x] employee with no report shouldn't be mentioned
 - [x] sort sheets by first name of employees
 - [x] sort reports by date rising (first day of month on the top)

**Comment by maciejSamerdak** [comment]
|_Better export reports to XLSX_

Oh yeah? And what if I don't? 😛
