### ISSUE TITLE
Feature not changing next report date

### ISSUE THREAD

**Issue by michalpiasecki1** [Code-Poets/sheetstorm#359]
current behaviour:
1. today is 01.07. I want to make reports for past days - lets say for a month. I am selecting 03.06 and creating report for that day
2. after creating report for 03.06, selected day is 01.07 again
3. report for 04.06, and date switch back to 01.07
and so on...

possible solution:
after creating report for 03.06 selected date for creating report should be 04.06 not 01.07

**Comment by kbeker** [comment]
@michalpiasecki1 You mean, you would like to have next day date after adding report? I think more intuitive would be if day won't change at all or change to the current day (current version). If someone would like to add few reports same day it would change him date every report. So maybe it would be good added value to application when date won't change at all but at start would be set at current day.

However you should add your reports every day and then you would not have any problems with date :D

**Comment by michalpiasecki1** [comment]
changing to current day seems to be worst solution. Right now, if someone is adding few reports per day it also changes selected date every report. Not changing date at all, when not direcly asked is slightly better. In date selection can be some logic as well, with some assumptions:

most people work 5 days per week, 8 hours per day, so:
if hours<8h: same day
hours=8h: next day

On the other hand, adding reports every day seems like impossible task :D

**Comment by kbeker** [comment]
> On the other hand, adding reports every day seems like impossible task :D

I am doing it every day :D

**Comment by Karrp** [comment]
> > On the other hand, adding reports every day seems like impossible task :D
> 
> I do it every day :D

The current version encourages regularity.
This is intended action.

By the way the idea of ​​dividing tasks into activity is to enter the report immediately after the activity.
For example:
development 2:00
meeting 1:00
development 5:00

I think we can close this issue.
@kbeker if you agree please close it.

**Comment by michalpiasecki1** [comment]
idea of shaping user behaviour over software decision is terrible design pattern - it never really worked

**Comment by kbeker** [comment]
@Karrp we had yesterday conversation in office that we won't enforce adding reports every day, but company rules might. So for this moment adding feature might has sense so lets leave it here ;)

**Comment by Karrp** [comment]
ok

**Comment by kbeker** [comment]
I see that it somehow related with #375. I'm closing it for now.

**Comment by kbeker** [comment]
I see that it somehow related with #375. I'm closing it for now.
