### ISSUE TITLE
Support Markdown in report description

### ISSUE THREAD

**Issue by Szymiks** [Code-Poets/sheetstorm#36]
Report description field is a common text field, so implementing markdown support helps this field to become more readable.

**Comment by rwrzesien** [comment]
I have discussed this today with @Szymiks and if I understood the case correctly, it is about adding possibility to display HTML tags in description field. From what I have tested, the solution used by @Szymiks only wraps content of the field `<p>` tags, like this:

```
markdown('text')                                                                                                                                           
Out[2]: '<p>text</p>\n'
```

If that solves the issue, then it is OK. But if the case is about adding possibility to edit `description` field with HTML content inside it, then we should take a different approach, which is:
1. Install https://github.com/django-ckeditor/django-ckeditor.
2. Change `description` field into `ckeditor_uploader.fields.RichTextUploadingField`.
3. Add migration.

That should do the case for admin panel. If we need to add WYSIWYG editor outside of the admin panel, this could help https://github.com/django-ckeditor/django-ckeditor#outside-of-django-admin.

@Karrp @Szymiks please take a look on this and share your thoughts.
