### ISSUE TITLE
Editting report - not read project and task activity from edited report?

### ISSUE THREAD

**Issue by bartoszbetka** [Code-Poets/sheetstorm#365]
For example, when I try to edit report `tech talk` with:
- `task activity: meeting` 
- `project: internal` 
I get: 
- `task activity: devops` 
- `project sheetstorm` 

This behavior will cause a lot of mistake in the reports.
I think the `task activity` and the `project` field come from the latest report, not from the edited report.

**Comment by kbeker** [comment]
Duplicated and done in https://github.com/Code-Poets/sheetstorm/pull/377
