### ISSUE TITLE
H:M input shouldn't be allowed in hours' mask

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#367]
The default behaviour is that H:M is passed as H:0M. This is troublesome and inconsistent with the mask. We should block out the H:M format and enforce two digits input for minutes.

Should be done:
 ------------
 - H:M input shouldn't be validated

**Comment by rwrzesien** [comment]
Sorry for being picky, but I think it should be:
``
H:M input should be validated as invalid.
```
