### ISSUE TITLE
Stats at the bottom of report list should involve reports from last 30 days.

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#368]
The percentage of hour worked per report, displayed below the list, should involve all reports from previous 30 days. This most likely involves the current month view, I believe the other months' stats should stay the way they are now.

Should be done:
 ------------
 - The percentage in current month should involve reports from last 30 days.

**Comment by rwrzesien** [comment]
@maciejSamerdak So summing it up:
1. If date is 15th of current month, it should show percentage from last 30 days.
2. If date is 15th of previous month, it should show percentage from that whole month?.

Is that correct?

**Comment by maciejSamerdak** [comment]
@rwrzesien Frankly, I'm not sure about that. Perhaps the whole last 30 days should only apply to the view on the current month and everything else should show percentage from whole month?

Unless it should always show last 30 days on every page.
@Karrp , you were discussing this with customer a while back. Do you remember the details?

**Comment by Karrp** [comment]
>Frankly, I'm not sure about that. Perhaps the whole last 30 days rule should only apply to the view on the current month and everything else should show percentage from whole month?

Thats right!
