### ISSUE TITLE
The Thursday dinner functionality

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#371]
To take under consideration and discuss further:
Sheet Storm could potentially handle dinner orders in more reliable way then google sheets. The concept is yet to be discussed.

Should be done:
 ------------
 - Consider whether Sheet Storm should handle dinner related functionality
 - Plan out the concept of the feature

**Comment by Karrp** [comment]
It's overkill for this app i think :(
