### ISSUE TITLE
Markdown support should be entirely removed from the app

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#374]
Markdown was considered unnecessary for daily report filling. Formatting in description field should only consider newlines, whitespaces and hyperlinks. Hyperlinks should be blue (customer decision).
There also should be migration to cut out all markdown related syntax from existing reports.

Should be done:
 ------------
 - Markdown support should be removed
 - Description field should display newlines, whitespaces
 - Description field should display clickable **hyperlinks** in blue font (in .xlsx should be black)
 - Markdown syntax should be cut out from existing reports

**Comment by dybi** [comment]
please, don't kill `markdown`!!!11oneoneone
