### ISSUE TITLE
On report editing, the task activity is set to default.

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#376]
When entering report editing, the task activity switches to the default one. This can result in changing the task activity to wrong one on editing, if the user doesn't notice the change.

NOTE: I found this on production, when I was editing my own report. The same thing might be happening with **the project** value, but I didn't have time to check it anymore. It should be checked as well.

Should be done:
 ------------
 - The task activity in report editing view should be the report's saved task activity and not the default one.

**Comment by kbeker** [comment]
@maciejSamerdak before you add some issue please check if task hasn't been added earlier. Duplicated with https://github.com/Code-Poets/sheetstorm/issues/365. I'm deleting #365
