### ISSUE TITLE
Recently selected activity conflicts with activity updating

### ISSUE THREAD

**Issue by and-kisorec** [Code-Poets/sheetstorm#380]
How to reproduce:
1. Create 1 activity item for selected date e.g. Internal + Other
2. Create second activity for the same date with different categories, e.g. `Synthia + Frontend development`
3. Try to update second activity: in the opened form we can see `Internal + Other` instead of `Synthia + Frontend development`

Should be done:
 ------------
 - Activity to update should have a stored category values, not recent and also not from firstly added activity

**Comment by kbeker** [comment]
Duplicated, already fixed and merged.
