### ISSUE TITLE
Notifications: Create NotificationType, Notification and NotificationEnabledForUser models

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#394]
Requires https://github.com/Code-Poets/sheetstorm/issues/393.

Create `NotificationType`, `Notification` and `NotificationEnabledForUser` models described in https://github.com/Code-Poets/sheetstorm/issues/76.

**Comment by Karrp** [comment]
Its big and interesting feature but for now we need something smaller.
Maybe later we will make the best Notifications :)
