### ISSUE TITLE
Notifications: Create admin models for Notification and NotificationEnabledForUser models.

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#395]
Requires https://github.com/Code-Poets/sheetstorm/issues/394.

`Notification` and `NotificationEnabledForUser` should be added to admin panel, with some basic data displayed on the list, some filtering and search options. This is up to the person implementing this to propose the setup.

**Comment by Karrp** [comment]
Its big and interesting feature but for now we need something smaller.
Maybe later we will make the best Notifications :)
