### ISSUE TITLE
Notifications: Project.is_enabled_notifications field

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#396]
Add `is_enabled_notifications` field to `Project` model according to https://github.com/Code-Poets/sheetstorm/issues/76 and handle it in `ProjectUpdateView` and other necessary places.

**Comment by kbeker** [comment]
At this moment I did not add this field anywhere. When this field will be needed in any case then it will be added :)

**Comment by Karrp** [comment]
Its big and interesting feature but for now we need something smaller.
Maybe later we will make the best Notifications :)
