### ISSUE TITLE
Notifications: New CustomUser fields

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#397]
Add new fields to `CustomUser` model according to https://github.com/Code-Poets/sheetstorm/issues/76  and handle it in `UserUpdateByAdmin` and other necessary places.

If possible, apply data migration, otherwise `reporting_managers` and `expected_weekly_hours` should be set by admin.

**Comment by Karrp** [comment]
Its big and interesting feature but for now we need something smaller.
Maybe later we will make the best Notifications :)
