### ISSUE TITLE
Notifications: Add `create_did_not_report_for_days_notifications` task

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#400]
Requires:
https://github.com/Code-Poets/sheetstorm/issues/394
https://github.com/Code-Poets/sheetstorm/issues/396
https://github.com/Code-Poets/sheetstorm/issues/397

Add `create_did_not_report_for_days_notifications` task according to https://github.com/Code-Poets/sheetstorm/issues/76.

**Comment by Karrp** [comment]
Its big and interesting feature but for now we need something smaller.
Maybe later we will make the best Notifications :)
