### ISSUE TITLE
Notifications: Add `NotificationsList` view

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#403]
Requires:
https://github.com/Code-Poets/sheetstorm/issues/394
https://github.com/Code-Poets/sheetstorm/issues/396
https://github.com/Code-Poets/sheetstorm/issues/397

Add `NotificationsList` view according to https://github.com/Code-Poets/sheetstorm/issues/76.

@Karrp @kbeker Should a separate task for creating template be added?

**Comment by Karrp** [comment]
Its big and interesting feature but for now we need something smaller.
Maybe later we will make the best Notifications :)
