### ISSUE TITLE
Better hours input in report creation

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#411]
I suggest:
When enter `3` next number should be enter after `:`.
When enter `2` and next number > `4` enter second digit after `:`
Same thing in minutes after enter `7`

**In brief**
_input -> output_
`2`, `4` -> `24:__`
`2`, `5` -> `02:5_`
`3` -> `03:__`
`3`, `7` -> `03:07`

Should be done:
 ------------
 - add bootstrap `Default Time Picker`

**Comment by maciejSamerdak** [comment]
I think it's st00pid and @Karrp succs!

**Comment by Karrp** [comment]
I think there should be some time picker maybe even in bootstrap.
https://mdbootstrap.com/docs/jquery/forms/time-picker/
On the bottom of site "Default Time Picker" should be good enough and have functionality which I meant.

@MartynaAnnaGottschling  Did you use "Default Time Picker" in your new design?
If yes, there is no problema :)

**Comment by Karrp** [comment]
> **In brief**
> _input -> output_
> `2`, `4` -> `24:__`
> `2`, `5` -> `02:5_`
> `3` -> `03:__`
> `3`, `7` -> `03:07`

@maciejSamerdak 
One markdown is worth 1000 words. ;)

**Comment by Merrique** [comment]
Moved to trello backlog
