### ISSUE TITLE
Crucial HTML elements should have an id

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#420]
All HTML elements that are interactive or contain crucial information should be assigned a unique `id` attribute to ease identification via automated Selenium browsing.

This requirement can be already satisfied by bootstrap classes or Django tags (eg. `{{ form }}` will already render all fields with unique ids). This can be verified by checking the source of a rendered page.

Should be done:
 ------------
 - All interactive elements (hyperlinks, form fields, buttons) should have an id, that's unique on page.
 - Elements that contain important information (eg. employee type) should have an id, that's unique on page.
 - Elements that are rendered in iteration (eg. edit buttons on list) should have an id, that contains object-related information (eg. user's id).
 - Elements rendered by JavaScript (eg. confirmation buttons) should also be assigned an id.

**Comment by dybi** [comment]
adding high priority label, as this is crucial to have automated acceptance tests/behavior tests

**Comment by maciejSamerdak** [comment]
This issue requires further discussion on which elements exactly should be given an id.

**Comment by rwrzesien** [comment]
@maciejSamerdak I think you should just go with the flow and add it based on the intuition. If it is blocking the tests it would be better to add something what we can improve later than waiting. I can describe some general suggestions which partially we discussed on rocket:
- `id` for unique elements on the whole side, `class` for repeatable.
- remember that Django by default add `id` to all form fields.
- think which elements are grouping others, try to add id/class to those elements only, and reach inner elements using xpath. Ie. if a form is a good candidate to have id/class, or some menu wrapping div, or footer wrapping div, etc. Think of if in the way that if you would like to move it to different template, you would have to change as little as possible.

**Comment by maciejSamerdak** [comment]
Closing according to comments by @rwrzesien Majority of elements will be retrieved by relative Xpaths from key container elements. The required ids will be given to grouping objects or key elements if considered necessary during tests' development.

Also the required _go with the flow_ approach beats the purpose of an issue, since there's no concrete fulfilment criteria.

**Comment by rwrzesien** [comment]
I am thinking about publishing book with quotes.
