### ISSUE TITLE
Display problem with export reports to CSV

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#434]
Should be done:
 ------------
 - moving cells as in the attached in this >  [jan_n-reports.csv.zip](https://github.com/Code-Poets/sheetstorm/files/3392333/jan_n-reports.csv.zip) file
   (after choosing the comma separator)

**Comment by Karrp** [comment]
@MartynaAnnaGottschling attach file as soon as possible.
Thank you :)

**Comment by MartynaAnnaGottschling** [comment]
![bug](https://user-images.githubusercontent.com/37015250/61217922-0f085e00-a711-11e9-9d31-ee06ed56e8a0.png)

**Comment by MartynaAnnaGottschling** [comment]
It was just a problem with the choice of how to import text (the separator was an unfortunate character '&', which also appeared in the name task_activity  :sweat_smile: ).

**Comment by MartynaAnnaGottschling** [comment]
It was just a problem with the choice of how to import text (the separator was an unfortunate character '&', which also appeared in the name task_activity  :sweat_smile: ).
