### ISSUE TITLE
Access permissions

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#45]
Users shouldn't see accounts of other users.
Now everyone have access everywhere just by typing right url address.

**URL** | **Permissions**
---------|------------------
`/user/NR/` | user with number NR
`/reports/author/` | admin
`/users/` | admin
`/users/NR/` | admin
`/managers/projects/` | admin, manager
`/managers/projects/create/` | admin, manager
`/managers/projects/NR/` | manager of project with number NR, admin
`/managers/projects/update` | manager of project with number NR, admin

**Comment by maciejSamerdak** [comment]
Users shouldn't see acounts of other users.
Now eweryone have access everywhere just by typing right url address.

**Comment by rwrzesien** [comment]
@Karrp @maciejSamerdak @kbeker 
What about following urls/views:

Employees:
- `/reports/` / ReportList -> I assume "author / manager of project / admin"
- `/reports/ID/` / views.ReportDetail -> I assume "author / manager of project / admin"
- `/reports/ID/delete/` / delete_report -> I assume "author / manager of project / admin"
- `/reports/management/ID/` / AdminReportView
- `/reports/project/ID/` / ProjectReportList
- `/reports/project/report/ID/` / ProjectReportDetail

Managers:
- `projects/ID/delete/` / ProjectDeleteView -> I assume "manager of project / admin"

**Comment by Karrp** [comment]
I think about editing & deleting users reports by manager. If manager can edit every part of report and make it empty, why can't he delete it?
I think in the future we will limit the number of fields editable by manager.

AdminReportView -> admin
ProjectReportList -> manager / admin
ProjectReportDetail -> manager / admin

UserCreate -> admin

Your assumptions are correct I think. :D
