### ISSUE TITLE
Add info in notifications telling which project the user has not entered the report for

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#480]
Every project should be mentioned in other line

**Email** | **Project** | **Days**
-----------|-------------|----------
user1@a.b | Project 1 | 2
user1@a.b | Project 2 | 5

Should be done:
 ------------
 - add column to table in notifications view

**Comment by kbeker** [comment]
I see that notifications are starting to getting bigger and bigger. What do you think about this feature @rwrzesien ? #MakeNotificationGreatAgain

**Comment by Karrp** [comment]
It's not just simple change which data you take from database?

**Comment by kbeker** [comment]
@Karrp At first sight, it's not :)
