### ISSUE TITLE
Use Code Poets colors

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#488]
To discuss

Use these colors:
![image](https://user-images.githubusercontent.com/37847362/62613048-fdc60200-b908-11e9-87b4-0aadf6d9f63b.png)

| RGB Color | Name |
| --- | --- |
| `#03428c` | `cp_blue1` |
| `#3777ba` | `cp_blue2` |
| `#40a6dc` | `cp_blue3` |
| `#88bb3b` | `cp_green` |
| `#d74141` | `cp_red` |
| `#ff6c17` | `cp_orange` |
| `#ffc03d`| `cp_yellow`|

Already used colors:

| RGB Color | Name |
| --- | --- |
| `#2c77bc` | `ss_blue` |
| `#f2f2f2` | `ss_background` |
| `#fafafa` | `ss_main_container` |
| `#e9efff` | `ss_logo_background` |

In the meantime, the company's color palette has changed. We should adapt to these changes.
Some buttons which are red or green should be company's colors.
If possible, make colors into constants. Like `black` means `#000000` in HTML.

Should be done:
 ------------
 - make above colors into constants (cp_green etc.)
 - replace already hard coded colors into constans colors

**Comment by kbeker** [comment]
@Karrp please specify exactly which buttons and on which colors should them be changed.
