### ISSUE TITLE
Refactor update account view in html as on mockups

### ISSUE THREAD

**Issue by Szymiks** [Code-Poets/sheetstorm#489]
Something between

![edit_user_account_details](https://user-images.githubusercontent.com/47628251/62618208-f1937200-b913-11e9-9003-3f5ffb095527.png)

and
![image](https://user-images.githubusercontent.com/37847362/62692240-9bd0cf80-b9d0-11e9-8cb1-8353b101e58f.png)

**Comment by Karrp** [comment]
Change order of fields

|  |  |
| --- | --- |
| First Name | Last Name |
|Email | Phone |
| Country | Phone |
| Country | Date |
| Admin |  |

Add buttons
Update, Discard, Change password, Delete

**Comment by Karrp** [comment]
Update because RODO

|  |  |
| --- | --- |
| First Name | Last Name |
| Email | User type |

**Comment by Merrique** [comment]
Copy of issue https://github.com/Code-Poets/sheetstorm/issues/497
