### ISSUE TITLE
Textarea in report list is not affected by majority of changes in .css file.

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#49]
Only resize parameter seems to affect the html display.

I guess it's an issue with bootstrap support. It probably overrides most of the changes that I make in my style.css. Will have to check how to make sure that my changes are on top.

**Comment by maciejSamerdak** [comment]
The bug has been resolved. It turned out I had to override bootstraps' form-control class in my style style.css.
The style class in style.css was defined as textarea.form-control, so it only affects the textarea.

**Comment by rwrzesien** [comment]
@Karrp According to @maciejSamerdak 
> The bug has been resolved. 

This can be closed I think.

**Comment by Karrp** [comment]
It will close with #19
