### ISSUE TITLE
new lines from description are not displayed properly

### ISSUE THREAD

**Issue by michalpiasecki1** [Code-Poets/sheetstorm#509]
creating report:
line1
line2
line3

result with:

> Date | Project | Task Activity | Work hours | Description
> Thursday, 08 August 2019 | Synthia | DevOps | 01:00 | line1 line2 line3

**Comment by kbeker** [comment]
Already fixed in next release. Closing

**Comment by michalpiasecki1** [comment]
it was not fixed, can you please reopen it?

**Comment by kbeker** [comment]
@Karrp please check this issue.

**Comment by Karrp** [comment]
@kbeker Issue is still valid

**Comment by michalpiasecki1** [comment]
this issue was still not resolved
