### ISSUE TITLE
Date* field is too small

### ISSUE THREAD

**Issue by orestlenczyk** [Code-Poets/sheetstorm#538]
I can see yyyy-mm-d but last digit is hidden

![Screenshot 2019-09-13 09 55 26](https://user-images.githubusercontent.com/41307518/64846484-0b0f9400-d60d-11e9-937f-0bd69f89e169.png)

**Comment by Karrp** [comment]
@michalpiasecki1 Works now properly?

**Comment by michalpiasecki1** [comment]
the bug is still here
