### ISSUE TITLE
Replace misleading names to the password fields

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#60]
Replace misleading name for password filed (password1) in users CustomRegisterSerializer class

**Comment by rwrzesien** [comment]
@Karrp With what values should they be replaced?

**Comment by Karrp** [comment]
Something like "repeated password"
But @MartynaAnnaGottschling said that "password1" is something from django custom user and change can be a problem

**Comment by rwrzesien** [comment]
This is separated - the password field name in code can be anything, but displayed name can be something else. We should focus on the displayed part here, and let the code and implementation handle the name on its own. 
This displayed name is currently autogenerated from serializer, but we are going to drop them soon in favor of Django forms.
So, do we want to change displayed name? I think then this ticket can be moved as a part of new design implementation.

**Comment by Karrp** [comment]
>  I think then this ticket can be moved as a part of new design implementation.

You'r right.

**Comment by kbeker** [comment]
It is already outdated.
