### ISSUE TITLE
Automatic user type

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#65]
### **Triggers**

- [x] **Admin change user_type of manager**
When manager's role has been removed for user (in detail form by admin), user should be removed from all project, where user is assigned as manager. This action should be preceded by a suitable message, like popup.

- [x] **User became manager**
When a user has been assigned to project as manager, user's user_type field should change automatically to MANAGER.

- [x] **User is no longer manager**
When a user is no longer manager of any project, user's user_type field should change automatically to EMPLOYEE.

**Comment by rwrzesien** [comment]
@Szymiks I think it would be best to achieve this using signals https://docs.djangoproject.com/en/2.1/ref/signals/#post-save.

@Karrp This issue https://github.com/Code-Poets/sheetstorm/issues/26 looks like a related to this one, but created some time before. Can this old one be closed?
