### ISSUE TITLE
Completed project shouldn't be suspended

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#70]
Project with `stop_date` (completed project) shouldn't be suspended.
It should trigger when `stop_date` changes from None to something else.

**Should be done**
----------------
 - create trigger in database like: if (stop_date != None) then suspended = False

**Comment by rwrzesien** [comment]
@Karrp @kbeker I have checked and it looks like this is already resolved, could you please test and verify, and if yes close the issue?

**Comment by Karrp** [comment]
Maybe we'll additionally use a trigger like:
if stop_date then terminated=True

related to #71

**Comment by rwrzesien** [comment]
@Karrp 

> Maybe we'll additionally use a trigger like:
> if stop_date then terminated=True

OK, so we actually want to mark the project with set `stop_date` as terminated, but instead of "terminated" use different term - is that correct?

**Comment by Karrp** [comment]
Yes it is
