### ISSUE TITLE
Notifications for manager if employee neglects his duties

### ISSUE THREAD

**Issue by Karrp** [Code-Poets/sheetstorm#76]
This description is in progress.

After writing some initial prove of concept, and thinking it through, I suggest that this issue will result in a quite big task, so it would be better to describe it first in a type of blueprint, and then split into smaller tasks.

**Models**

1. NotificationType (enum)
- DID_NOT_REPORT_FOR_DAYS
- HAS_LESS_HOURS_IN_WEEK
- HAS_MORE_HOURS_IN_WEEK
- HAS_LESS_PERCENTAGE_OF_HOURS_IN_WEEK
- HAS_MORE_PERCENTAGE_OF_HOURS_IN_WEEK
- USER_WEEKLY_HOURS
- HAS_LESS_HOURS_IN_DAY
- HAS_MORE_HOURS_IN_DAY

2. Notification (new model)
This represents single notification of given type for given user in given project, received by given manager (or other user).

| Field name | Field type | Is null | Description |
| --- | --- | --- | --- |
| user | FK CustomUser | not null | CustomUser object which this notification is about. |
| receiver | FK CustomUser | not null | CustomUser object which is a receiver of this notification. |
| project | FK Project | not null	| Project which given user notification is about. |
| type | NotificationType | not null | Type of notification from NotificationType. |
| created_at | DATETIME | not null | Time when notification was created. |
| is_read_at | DATETIME | null | When null, it means that notification was not yet read. |

3. NotificationEnabledForUser (new model)
This represents if given user in given project has enabled notification of given type for given receiver.

| Field name | Field type | Is null | Description |
| --- | --- | --- | --- |
| user | FK CustomUser | not null | CustomUser object which this notification is about. |
| type | NotificationType | not null | Type of notification from NotificationType. |
| is_enabled | BOOL | not null | Determines if notification of given type for given user in given project is enabled to be received by given manager. |
| values | JSON | not null, defualt `{}` | Contains data specific for given notification type. |
| modified_at | DATETIME | not null | Time when notification for user was enabled or disabled last time. |
| modified_by | FK CustomUser | not null, default project creator | User who enabled or disabled notification for user last time. |

`user` and `type` should be unique together.

4. Project (new field)

| Field name | Field type | Is null | Description |
| --- | --- | --- | --- |
| is_enabled_notifications | BOOL | not null | Default `True`. Determines if notifications are globally enabled for given project. |

5. Custom user (new fields)

| Field name | Field type | Is null | Description |
| --- | --- | --- | --- |
| is_enabled_notifications | BOOL | not null | Default `True`. Determines if notifications are globally enabled for given user. | 
| reporting_managers | ManyToMany CustomUser | null | Reporting managers for this users, only them will receive notifications for this user. | 
| expected_weekly_hours | timedelta | null | Number of hours user is expected to report weekly. | 

6. TaskActivityType (new type)
Add `Holidays` as task activity type. This type should be excluded from exporting and counting to total hours sum, but counted for notifications limits.

**Signals**
1. Project.members.m2m_changed.
When member is removed from project, all NotificationEnabledForUser for this user and project should be removed.

**Celery**
There This will require periodic tasks which will create notifications, so lets use celery to do the job.

Tasks:
1. create_did_not_report_for_days_notifications.
Runs once a day. This task should create notifications for each user that did not report in given project for X days (X is defined in `NotificationEnabledForUser.values` field`)

2. create_weekly_notifications.
Runs once a week on last day of a week. This task should create notifications for each user if:
- he has report less hours than X in current week (X is defined in `NotificationEnabledForUser.values` field`).
- he has report more hours than X in current week (X is defined in `NotificationEnabledForUser.values` field`)
- has less than X percentage of hours in a week (X is defined in `NotificationEnabledForUser.values` field`).
- has more than X percentage of hours in a week (X is defined in `NotificationEnabledForUser.values` field`).
- has `USER_WEEKLY_HOURS` enabled.

3. create_daily_notifications.
Runs once a day. This task should create notifications for each user if:
- he has report less hours than X in current day (X is defined in `NotificationEnabledForUser.values` field`).
- he has report more hours than X in current day (X is defined in `NotificationEnabledForUser.values` field`).

Each task should take into consideration `Project.is_enabled_notifications` and `CustomUser.is_enabled_notifications` values.

**Views**

1. Notifier (new widget).
In main template there should be a notifier, in example in graphical form of exclamation mark, that will indicate that there are new, unread notifications for currently logged user.

2. NotificationsList (new view).
This should display list of all notifications received by current user. It should be paginated. It should be possible to filter out:
- particular project.
- particular user.
- particular notification type.
- notifications between datetimes range.

3. ProjectUpdateView (view update).
Admin should have possibility to globally enable/disable notifications for given project.

4. UserUpdateByAdmin (view update).
Admin should have possibility to globally enable/disable notifications for given user and set his `reporting_managers`.

5. ManagerNotificationSettings (new view).
Every manager can set notifications for users to which he is assigned as `reporting_manager`. By default no notification are created, so manager will have to setup them first. If there are more than one reporting manager, any of them can set users notifications, but the latest one making change will be remembered and displayed.
From UX perspective this can be done like this: 
- First template show list of projects with list of users in each projects, and summary of their enabled/disabled notifications.
- When clicking in given user, there could be a form to enable/disable notifications of each type for given user in given project.

**Admin**

`Notification` and `NotificationEnabledForUser` should be added to admin panel, with some basic data displayed on the list, some filtering and search options.

**Comment by rwrzesien** [comment]
This description is in progress.

After writing some initial prove of concept, and thinking it through, I suggest that this issue will result in a quite big task, so it would be better to describe it first in a type of blueprint, and then split into smaller tasks.

**Models**

1. NotificationType (enum)
- DID_NOT_REPORT_FOR_DAYS
- HAS_LESS_HOURS_IN_MONTH
- HAS_MORE_HOURS_IN_MONTH
- HAS_LESS_HOURS_IN_WEEK
- HAS_MORE_HOURS_IN_WEEK
- HAS_LESS_HOURS_IN_DAY
- HAS_MORE_HOURS_IN_DAY


2. Notification (new model)
This represents single notification of given type for given user in given project, received by given manager (or other user).

- user 		CustomUser	not null		CustomUser object which this notification is about.
- receiver	CustomUser	not null		CustomUser object which is a receiver of this notification.
- project	Project		not null		Project which given user notification is about.
- type		ENUM		not null		Type of notification from NotificationType.
- created_at	DATETIME	not null		Time when notification was created.
- values	JSON		not null/defualt{}	Contains data specific for given notification type.
- is_read_at    DATETIME	null			When null, it means that notification was not yet read.


3. NotificationEnabledForUser (new model)
This represents if given user in given project

- user 		CustomUser	not null		CustomUser object which this notification is about.
- receiver	CustomUser	not null		CustomUser object which is a receiver of this notification.
- project	Project		not null		Project which given user notification is about.
- is_enabled	BOOL		not null		Determines if notification of given type for given user in given 								project is enabled to be received by given manager
- type		ENUM		not null		Type of notification from NotificationType.


4. Project (new field)

- is_enabled_notifications	BOOL	not null	Determines if notifications are enabled for given project.


5. Custom user (new field)

- is_enabled_notifications	BOOL	not null	Determines if notifications are enabled for given user.


*Signals*

1. Project.post_save.
When project is created, NotificationEnabledForUser for all types, users and receivers should be created for this project.

2. Project.members.m2m_changed.
When member is added to a project, NotificationEnabledForUser for all types and receivers should be created for this user and project.
When member is removed from project, all NotificationEnabledForUser for this user and project should be removed.

3. Project.managers.m2m_changed.
When manager is added to a project, NotificationEnabledForUser for all types and users should be created for this receiver and project.
When manager is removed from project, all NotificationEnabledForUser for this receiver and project should be removed.


*Celery*
There This will require periodic tasks which will create notifications, so lets use celery to do the job.

Tasks:
1. create_did_not_report_for_days_notifications 


2. create_has_less_hours_in_month_notifications
2. create_has_less_hours_in_month_notifications
2. create_has_less_hours_in_month_notifications
2. create_has_less_hours_in_month_notifications
2. create_has_less_hours_in_month_notifications
2. create_has_less_hours_in_month_notifications
2. create_has_less_hours_in_month_notifications

Each task should take into consideration `Project.is_enabled_notifications` and `CustomUser.is_enabled_notifications` values.


*Views*

1. Notifier.
In main template there should be a notifier, in example in graphical form of exclamation mark, that will indicate that there are new, unread notifications for currently logged user.

2. NotificationsList.
This should display list of all notifications received by current user. It should be paginated. It should be possible to filter out:
- particular project.
- particular user.
- particular notification type.
- notifications between datetimes range.

3. ProjectUpdateView.
Admin should have possibility to enable/disable notifications for given project.

4. UserUpdateByAdmin.
Admin should have possibility to enable/disable notifications for given user.

5. ManagerNotificationSettings.

*Admin*

`Notification` and `NotificationEnabledForUser` should be added to admin panel, with some basic data displayed on the list, some filtering and search options.

**Comment by kbeker** [comment]
1. We need distinguish between work day and vacation day, so I think that we need to add functionality for all employees when they have free day when not. I think that this one might be quite big task.
2. Everything what is related with notification should be in new app for better readbility.
3. After conversation with @rwrzesien we conviced me that celery is better than cron because celery might be needed later.
4. `HAS_LESS_HOURS_IN_DAY` and `HAS_MORE_HOURS_IN_DAY`. We will need to set somewhere the number of daily hours. I think that it should be personal and also added to `CustomUser` model, because some people work 8 hours per day and other like for example interns/students work less than 8 hours and I think it shouldn't be pointed as notification that something is wrong.
5. Same situation as in point 4 with others notifications types.
6. Is `NotificationEnabledForUser` model would be used for puropse which I have mentioned in 4 and 5 points? If not what other values would be added in `values` field?
7. 

> create_has_less_hours_in_month_notifications. Runs once a on last day of a month. This task should create notifications for each user if he has report less hours than X in current month (X is defined in NotificationEnabledForUser.values field).

I would run this task in first day of new month instead of last day. All tasks which you mentioned as they should run on last day I would run in first day of new month :)

8. Also I think that we could extend this task also for notifications for users. Maybe even sent them on mailbox? But we would need also decision from Adrian about mail server and research from @bartoszbetka

**Comment by kbeker** [comment]
9. Also now I think that values for `HOURS_IN_MONTH` should be dynamically set - I mean that for example in february we have less work day than in july or august.

**Comment by rwrzesien** [comment]
@kbeker 
> 1. We need distinguish between work day and vacation day, so I think that we need to add functionality for all employees when they have free day when not. I think that this one might be quite big task.

I agree with both (it should be done and will be big task) so I think we should do this separately. For now it could be accomplished by manually disabling notification for given user by manager, or by just ignoring it.
But I can think about relatively quick feature, like user (or admin for all users) can set a flag `holiday_mode` which will then hold on from creating `DID_NOT_REPORT_FOR_DAYS` notification. It should also disable adding/editing reports by user, so he will remember to turn it off.

> 2. Everything what is related with notification should be in new app for better readbility.

I agree, I will add this to the description.

> 4. HAS_LESS_HOURS_IN_DAY and HAS_MORE_HOURS_IN_DAY. We will need to set somewhere the number of daily hours. I think that it should be personal and also added to CustomUser model, because some people work 8 hours per day and other like for example interns/students work less than 8 hours and I think it shouldn't be pointed as notification that something is wrong.

In my concept it is configurable for each user in each project for each receiver in `NotificationEnabledForUser.values` field. But I agree I didn't explained this properly, and wanted to explain it on the meeting. I will also think about explaining it better in description.
I also think this would rather be used for extreme cases, like less than 1 hour reported per day or more than 20.

> 5. Same situation as in point 4 with others notifications types.

Same here, it will be in `NotificationEnabledForUser.values` for each user in each project for each receiver.

> 6. Is NotificationEnabledForUser model would be used for puropse which I have mentioned in 4 and 5 points? If not what other values would be added in values field?

Yes exactly :) I assume that some more complex notifications that we might add later would require more values defined, so to keep it flexible I suggest keeping it in JSON type field for now.

> 7. I would run this task in first day of new month instead of last day. All tasks which you mentioned as they should run on last day I would run in first day of new month :)

Yes, what I have in mind that they should run overnight, between last day of last month and first of new one. Some for other, they should run overnight (or we can ie. allow to define time buffer in `values`).

> 8. Also I think that we could extend this task also for notifications for users. Maybe even sent them on mailbox? 

As discussed, user notifications will be skipped for now.

> 9. Also now I think that values for HOURS_IN_MONTH should be dynamically set - I mean that for example in february we have less work day than in july or august.

Good point, I have first assumed that it will be used for extreme cases like less than 50 hours for regular employee, or over 250 hours. But if some manager would like to have those values set tighter, it might be an issue. Also, if during a month (or week too) employee will have holidays, this will be triggered more easily. This is something we could discuss tomorrow.
One quick way around this for now would be to add `Holidays` as activity type.

**Comment by rwrzesien** [comment]
I will move my comment to issue description and modify it on the stuff we discussed during meeting:
- make notifications settings for user global, not per project.
- remove `receiver` from `NotificationEnabledForUser` model.
- add `reporting_managers` field to `CustomUser` model. Those managers will receive notifications for given user.
- Add `Holidays` as task activity type. This type should be excluded from exporting and counting to total hours sum.
- Remove `montly` type of notifications.
- Every configurable time should follow the rule of minutes be multiplication of 15.

**Comment by Karrp** [comment]
Thank you @rwrzesien for your work on this task. I'm impressed.
Unfortunately, after talking to the client and confronting results with team during the standup, we have determined that for the time being we will do the simplest yet functional notifications of the non-entered reports.
However, I hope that we will come back to your solution in the future.  :)

**Comment by Karrp** [comment]
Thank you @rwrzesien for your work on this task. I'm impressed.
Unfortunately, after talking to the client and confronting results with team during the standup, we have determined that for the time being we will do the simplest yet functional notifications of the non-entered reports.
However, I hope that we will come back to your solution in the future.  :)

**Comment by rwrzesien** [comment]
@Karrp Sure no problem, I hope this will come back at some point.
