### ISSUE TITLE
Add mail server to sheetstorm

### ISSUE THREAD

**Issue by bartoszbetka** [Code-Poets/sheetstorm#79]
We decided for now to use existing `sendgrid` account as mail server for `django` app. This solution has some limitations. The configuration settings are already added. 

The `EMAIL_BACKEND` setting need to be added to the `base.py` file. It should contains: `EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'`

**Comment by kbeker** [comment]
Tests: https://docs.djangoproject.com/en/2.1/topics/email/#quick-example

**Comment by Karrp** [comment]
@bartoszbetka Pleas add this issue to Sheet Storm project

**Comment by MartynaAnnaGottschling** [comment]
@bartoszbetka Can I use and test it locally? Then it's just adding this setting or should I do something more?
