### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by maciejSamerdak** [Code-Poets/sheetstorm#83]
This is related to issue #68, but the problem seems to be broader, so I'm posting this separately.

_sheetstorm/utils/base_tests.py_, line **122** returns an error, such as **_AssertionError: FakeDatetime(2019, 3, 6, 14, 41, 33, 947105, tzinfo=<UTC>) != FakeDatetime(2019, 3, 6, 14, 41, 33, 947105)_** **ONLY IF** we have a TIME_ZONE configured in local settings (as _Europe/Warsaw_).
- The first value is stored in the database, in an **automated DateTimeField**.
- The second value is a result of calling **datetime.datetime.now()**

I understand that the issue is lack of timezone info in **datetime.now()** result. But for instance,  **.timestamp()** presented in **float** gives a **1 hour** offset between the two values.

Okay, so the **datetime.now()** must be returning time in local timezone setting, right?

Okay, now we're getting to the good part: we have a **.now()** method and a **.utcnow()** method to specifically return UTC time. And guess what? Here, both **datetime.now()** and **datetime.utcnow()** will return **THE SAME VALUE!**

BUT, if I use **.astimezone()** and I convert it to the UTC, **datetime.astimezone(timezone.utc)** NOW it returns an hour earlier!

```
ipdb> datetime.datetime.now()                                                   
FakeDatetime(2019, 3, 6, 14, 42, 20, 717704)
ipdb> datetime.datetime.utcnow()                                                
FakeDatetime(2019, 3, 6, 14, 42, 20, 717704)
ipdb> datetime.datetime.now().astimezone(datetime.timezone.utc)                 
FakeDatetime(2019, 3, 6, 13, 42, 20, 717704, tzinfo=datetime.timezone.utc)
```

And it seems no matter what combination I try, if I convert both compared values to same timezone there will ALWAYS be this offset!

Does anyone have any idea what on earth is going on here? To me it seems like Python itself dropping a ball here. I have no idea how to fix this thing, except for maybe not configuring the local timezone at all.

I found [this thread](https://stackoverflow.com/questions/20804837/weird-astimezone-behavior). Maybe it's related with this issue?

**Comment by maciejSamerdak** [comment]
Okay, I figured out this workaround. Does it seems reasonable enough?
```
    def field_auto_now_test(self, auto_field, update_field, value):
        with freeze_time(datetime.datetime.now().astimezone(datetime.timezone.utc)) as frozen_datetime:
            # so now frozen time is UTC for sure
            model = self.default_model()
            model.full_clean()
            model.save()
            frozen_datetime.tick()
            setattr(model, update_field, value)
            model.full_clean()
            model.save()
            current_value = getattr(model, auto_field)
            self.assertEqual(current_value.replace(tzinfo=None), datetime.datetime.now())
            # so now the values will be equal because of no timezone parameter and weird conversion issues are gone
```
Seriously though, what's the deal with those timezones doing such poor job existing?

**Comment by kbeker** [comment]
@maciejSamerdak I checked how we handle this problem in Concent and this is what I found:
```python
import calendar
from django.utils import timezone


def get_current_utc_timestamp() -> int:
    """
    Returns current timestamp as int.
    Returned timestamp is guaranteed to be in UTC on systems where epoch is January 1, 1970, 00:00:00 (UTC).

    """
    current_timestamp = int(timezone.now().timestamp())
    assert calendar.timegm(time.gmtime()) - current_timestamp <= 1
    return current_timestamp
```

At first sight, it looks like it's enough to change `datetime.datetime.now()` to function presented above?

**Comment by Karrp** [comment]
@maciejSamerdak Please add this issue to Sheet Storm project

**Comment by maciejSamerdak** [comment]
@kbeker Thanks! I'll see if it fixes the problem.

**Comment by maciejSamerdak** [comment]
Using **django.utils.timezone** instead of **datetime.datetime** did the trick. I'm still baffled by the issue though.

**Comment by rwrzesien** [comment]
@maciejSamerdak The case with timezones always depend on how you want to handle timezones in application. There are some business logic questions that should be answered, and then solution should be adapted to what is needed.

The question that could be asked are:
1. Do I have to care about timezones in my application?
2. If yes, are there any datetimes being sent by user? If yes, how should they be parsed/stored?
3. Do I have to care about getting user location and adapting displayed datetimes to user current timezone?

And possibly more. So in this case I assume we want to show and accept all datetimes in `Europe/Warsaw` timezone? Then setting `TIMEZONE="Europe/Warsaw"` and using `timezone.now()` everywhere should do the case.

> And it seems no matter what combination I try, if I convert both compared values to same timezone there will ALWAYS be this offset!

I get different results while using `python manage.py shell` while being on sheetstorm virtual env:
```
In [1]: import datetime                                                                                                                                   
In [2]: datetime.datetime.now()                                                                                                                           
Out[2]: datetime.datetime(2019, 3, 8, 16, 58, 0, 521381)
In [3]: datetime.datetime.utcnow()                                                                                                                        
Out[3]: datetime.datetime(2019, 3, 8, 15, 58, 8, 774171)
In [4]: datetime.datetime.now().astimezone(datetime.timezone.utc)                                                                                         
Out[4]: datetime.datetime(2019, 3, 8, 15, 58, 15, 107552, tzinfo=datetime.timezone.utc)
```

This is after setting `Europe/Warsaw` in Django settings. Was yours after or before that setting?

**Comment by rwrzesien** [comment]
As discussed, the reason why `datetime.datetime.now()` and `datetime.datetime.utcnow()` returns the same results is that it is coming from `FakeDatetime` class, which has its own custom implementation of `utcnow()` method.
