### ISSUE TITLE
Make `BaseModelTestCase` a mixin class

### ISSUE THREAD

**Issue by rwrzesien** [Code-Poets/sheetstorm#96]
Currently `BaseModelTestCase` inherits from `django.tests.TestCase` class, which inherits from `unittest.TestCase`, but most of the code it contains are helpers that are not strictly related to `TestCase` class. Those helpers should be move to separate `mixin` class, so the test classes which will use them, can still inherit from different `TestCase` classes (like `django.tests.TestCase` and `django.tests.TransactionTestCase`.

**Comment by Merrique** [comment]
Move to trello backlog
